# Generated by Django 6.0.7 on 2026-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="visit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
